# Generated by Django 4.2.1 on 2023-07-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_headline_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='description',
            field=models.TextField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='headline',
            name='image',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='headline',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
